### ISSUE TITLE
minor: sum_to_10 never introduced

### ISSUE THREAD

**Issue by ncbaratta** [PacktPublishing/The-Python-Workshop-Second-Edition#11]
On page 97 there is a line of code that says 'from sum_to_10 import result' but no where before that was it explained that the code above that was sum_to_10.

**Comment by rajat-packt** [comment]
Hey @ncbaratta, the examples on page 97, were given to demonstrate the effects of the "__name__ == ‘__main__’" statement.
They have been made with the assumption that the readers will pick up on that the file needs to be saved with the name "sum_to_10" (based on Exercises 36 &37).
Sorry if that did not appear to be as apparent. Thanks for your feedback!
