### ISSUE TITLE
activity 4 on page 46 doesn't match answer

### ISSUE THREAD

**Issue by ncbaratta** [PacktPublishing/The-Python-Workshop-Second-Edition#4]
Activity 4 on page 46 says to use the f-string to output the results, but the answer in the appendix doesn't do that.

**Comment by coreyjwade** [comment]
This is a case where either way is okay. f-strings were used more in the 2nd edition as they have become more standard but the appendix was not updated. The appendix should be updated.

**Comment by coreyjwade** [comment]
Also note that the answer in terms of the output is the exact same. Files have been updated with f-strings.
